services:
  - type: worker
    name: total-scraper-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: APIFY_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: META_AD_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: BOT_EMAIL
        sync: false
      - key: BOT_APP_PASSWORD
        sync: false
      - key: INVITE_CODE
        sync: false